version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: rootuser
      POSTGRES_PASSWORD: mysecret123
      POSTGRES_DB: ticketdb
    ports:
      - "5433:5432" 
